LIBSTLPORT_PORT_DIR := $(call select_from_ports,libstlport)
LOCAL_PATH := $(LIBSTLPORT_PORT_DIR)/src/lib/stlport

BIONIC_PORT_DIR := $(call select_from_ports,bionic)

libstlport_src_files := \
	src/dll_main.cpp \
	src/fstream.cpp \
	src/strstream.cpp \
	src/sstream.cpp \
	src/ios.cpp \
	src/stdio_streambuf.cpp \
	src/istream.cpp \
	src/ostream.cpp \
	src/iostream.cpp \
	src/codecvt.cpp \
	src/collate.cpp \
	src/ctype.cpp \
	src/monetary.cpp \
	src/num_get.cpp \
	src/num_put.cpp \
	src/num_get_float.cpp \
	src/num_put_float.cpp \
	src/numpunct.cpp \
	src/time_facets.cpp \
	src/messages.cpp \
	src/locale.cpp \
	src/locale_impl.cpp \
	src/locale_catalog.cpp \
	src/facets_byname.cpp \
	src/complex.cpp \
	src/complex_io.cpp \
	src/complex_trig.cpp \
	src/string.cpp \
	src/bitset.cpp \
	src/allocators.cpp \
	
	
libstlport_src_files_c := \
	src/c_locale.c \
	src/cxa.c \

libstlport_c_includes := \
	$(LOCAL_PATH)/stlport \
	$(BIONIC_PORT_DIR)/include \
        $(BIONIC_PORT_DIR)/include/libstdc++ \
        

libstlport_cflags := -D_GNU_SOURCE \
	-D__ANDROID__
	
libstlport_cppflags := -fuse-cxa-atexit
